- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0  # Use the ref you want to point at
  hooks:
    - id: trailing-whitespace
      exclude: '^vendor/.*$'
    - id: end-of-file-fixer
      exclude: '^vendor/.*$'
    - id: check-added-large-files
      exclude: '^vendor/.*$'
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
#    - id: go-fmt
    - id: go-mod-tidy
      exclude: '^vendor/.*$'
